version: '3.7'

services:
  kotenet_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  kotenet_db:
    image: postgres:13
    volumes:
      - kotenet_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  kotenet_postgres_data: